title: The Old Ways
lang: en-US
author: Joakim Hertze
email: social@hertze.com
description: Exploring how the good old-fashioned ways may still be relevant in today’s world.
baseurl: ""
url: "http://oldways.se"
twitter_username: hertze
github_username:  hertze
paginate: 5

# Set this to true to include comments, otherwise to false.
staticman: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
