title: The Old Ways
lang: en-US
author: Joakim Hertze
email: social@hertze.com
description: An exploration of the good old-fashioned ways of making a life.
baseurl: ""
url: "https://oldways.se"
enforce_ssl: oldways.se
twitter_username: hertze
github_username:  hertze
paginate: 5
permalink: /:year/:month/:day/:title

# Set this to true to include comments, otherwise to false.
staticman: false

# No future posts
future: false

# Build settings
markdown: kramdown
theme: 
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
