title: The Old Ways
author: Joakim Hertze
email: social@hertze.com
description: An open exploration of how the good old ways might sometimes be just what you need.
baseurl: ""
url: "http://oldways.se"
twitter_username: hertze
github_username:  hertze
paginate: 5

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
